name: test_python
on: [pull_request, push]
jobs:
  test_python:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          - test_application.py
          - test_argparse_to_json.py
          - test_checkbox.py
          - test_chooser_results.py
          - test_cmd_args.py
          - test_common.py
          - test_config_generator.py
          - test_constraints.py
          - test_counter.py
          - test_dropdown.py
          - test_filterable_dropdown.py
          - test_filtering.py
          - test_formatters.py
          - test_header.py
          - test_listbox.py
          - test_numeric_inputs.py
          - test_options.py
          - test_parent_inheritance.py
          - test_password.py
          - test_processor.py
          - test_radiogroup.py
          - test_slider.py
          - test_textarea.py
          - test_textfield.py
          - test_time_remaining.py
          - test_util.py 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip wheel
      - run: pip install pytest wxPython
      - run: pip install --editable .
      - run: pythonw3 -m pytest gooey/tests/${{ matrix.test }}
      #- run: pytest . || true
      #- uses: GabrielBB/xvfb-action@v1
      #  with:
      #    run: pytest gooey/tests/${{ matrix.test }}
