name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 isort mypy pyupgrade-directories safety
      - run: bandit --recursive --skip B101,B307,B404,B602,B603,B605,B607 .
      - run: black --check . || true
      - run: codespell --ignore-words-list="datas,metatdata,strat" --skip="*.json"
      - run: flake8 . --count --builtins=_ --max-complexity=18 --max-line-length=233
                      --select=E5,E9,F63,F7,F82 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-line-length=88 --show-source --statistics
      - run: isort --profile black . || true
      - run: pip install wxPython
      - run: pip install --editable .
      - run: mkdir -p .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive . || true
      - run: pyupgrade-directories --py36-plus . || true
      - run: safety check
